packages:
  - packages/*

# Dependencies that may be built
onlyBuiltDependencies:
  - esbuild

# Scripts needed in each individual package
requiredScripts:
  - build
  - test

# Ensure all peer dependencies are installed and correct
strictPeerDependencies: true

# Save all dependencies using exact versions
savePrefix: ""

catalog:
  "@arethetypeswrong/core": 0.18.5
  tsdown: 0.22.13
  type-fest: "5"
  typescript: 6.0.3
  vitest: 4.1.10
