name: CI

on:
  workflow_call:
  pull_request:

jobs:
  ci:
    name: CI (Node.js ${{ matrix.node-version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [22, 24, 26]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install

      - run: pnpm lint

      - run: pnpm spelling:check

      - name: Check for README changes
        run: |
          pnpm run sync:readme
          git diff --exit-code README.md

      - run: pnpm format:check

      - run: pnpm test

      - run: pnpm build
